### ISSUE TITLE
Cannot install on Synology NAS Home Assistant

### ISSUE THREAD

**Issue by seveny42** [DeerMaximum/ha-addons#4]
Hi, when I follow the link in
This integration requires the Coe to HTTP add-on.
it will redirect me to my dockerized HA and then show the error message:

Diese Weiterleitung wird von deiner Home Assistant-Installation nicht unterstützt. Benötigt entweder das Home Assistant-Betriebssystem oder die Home Assistant Supervised-Installationsmethode. 

How can I make it work then? Is there a way to manual install it?

Sven

**Comment by seveny42** [comment]
Thank you, my SYN accepted the amd64-package and I configured the CoEToHTTP now to this server. Installation successfull. Activated the debuglog since I cannot see any values coming in. 
Am I missing the config part that it should "talk" to the CMI somehow?
Is there anything else to "activate" or "configure"?

**Comment by seveny42** [comment]
I think I now found 2 new values in main Node1 (not node 50 as expected), maybe they are mapped to node 1 for some reason?

History suggests that this values were already available with the initial installation of the "CMI integration" and the CoEToHTTP was not necessary!?
 
Node: 1 - Network-Analog 1 19.8 °C 
Node: 1 - Network-Analog 2 51.3%

**Comment by DeerMaximum** [comment]
If you have configured CoE on the CMI, then the CMI sends the data to the CoE to HTTP server, which is read by the integration.

You must reload the integration in HA when you add or delete a value from your CoE configuration, to make the changed visible.
